acme_sylius_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: AcmeSyliusExamplePlugin:Greeting:staticallyGreet
        name: ~

acme_sylius_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: AcmeSyliusExamplePlugin:Greeting:dynamicallyGreet
        name: ~

acme_sylius_gift_unwrapper:
    path: /unwrap/{id}
    defaults:
        _controller: acme.sylius_example_plugin.controller.unwrap_controller
